export const Question= [
    { id:"1",
      prompt: "What is my name?",
      optionA: "John",
      optionB: "Jake",
      optionC: "Josh",
      optionD: "Pedro",
      answer: "optionD",
    },
    {
        id:"2",
      prompt: "Which of this is not a programming language?",
      optionA: "Python",
      optionB: "JavaScript",
      optionC: "MC-03",
      optionD: "Java",
      answer: "optionC",
    },
    {
        id:"3",
      prompt: "Which of this is not a javascript framework?",
      optionA: "React",
      optionB: "Angular",
      optionC: "Vue",
      optionD: "Java",
      answer: "optionD",
    },
    {
        id:"4",
        prompt: "Which of this is not a javascript framework?",
        optionA: "React",
        optionB: "Angular",
        optionC: "Vue",
        optionD: "Java",
        answer: "optionD",
      },
      { id:"5",
        prompt: "Which of this is not a javascript framework?",
        optionA: "React",
        optionB: "Angular",
        optionC: "Vue",
        optionD: "Java",
        answer: "optionD",
      }
  ];